### PR TITLE
Fixes a typo, IP in (ip netns) to ip 

### PR DESCRIPTION
**Pull request by Mohamed-AH**
This PR…Fixes a typo. changed "IP"  (ip netns) to ip

### CODE REVIEW

**Review by dipankardas011 — COMMENTED** [review]
@Mohamed-AH it is a Linux command so this PR is not valid

**Comment by Mohamed-AH** [comment]
ok but it throws an error.

**Comment by saiyam1814** [comment]
Valid PR, caps will give an error for that command. Thanks @Mohamed-AH for the PR

**Comment by dipankardas011** [comment]
@Mohamed-AH sorry for my incorrect review maybe at that time seen the reverse and commented

**Comment by Mohamed-AH** [comment]
@saiyam1814 @dipankardas011 thank you.

**Pull request merged**
